---
title: "TR AQPP Data Analysis and Graphics"
output: html_notebook
---

```{r}
#HOUSEKEEPING

library("ggplot2")
library('plyr') # always load plyr before dplyr
library("dplyr")
library("tidyr")
library("stringr")
library("lubridate")

#global graph settings (font size, etc.)
theme_set(theme_gray(base_size = 16)) #theme_gray is the default theme

#import app results spreadsheets
app_timeseries <- read.csv('~/Google Drive/WEEL/Tres Rios/datasets/tr-aquatic-primary-productivity/results/tr_app_timeseries.csv', stringsAsFactors = FALSE)
app_timeseries <- mutate(app_timeseries, date = mdy(date))

```


```{r}
#graphing

#anpp plot
anpp_timeseries_plot <- ggplot(data = app_timeseries, aes(x = date)) + #calls ggplot and stores the call in a graphics object called "app_timeseries_plot"
  geom_point(aes(y = anpp_mean, color = "ANPP"), size = 3)+ #plots our data as points, specify our data series via a color argument (to be defined later)
  geom_errorbar(mapping=aes(x=date, ymin=anpp_mean-anpp_std_err, ymax=anpp_mean+anpp_std_err), width=7, size=0.5, color="dark green")+ #defines the size and values for standard error
  #formatting commands below
  scale_x_date(date_breaks="1 month", date_labels ="%b-%y", limit = c(as.Date("2017-05-01"), as.Date("2017-12-01")))+ #sets the scale for x axis
  coord_cartesian(ylim=c(0,0.8))+ #defines viewable area of the graph (different from ylim in that this only adjusts viewing area) (otherwise R just guesses)
  labs(x = "Date", y = "ANPP (mg/hr)")+ #sets labels for each axes
  theme(legend.position=c(0.9,0.9))+ #positions read as (x,y), where x = 0 is left, y = 0 is bottom
  theme(legend.key=element_rect(fill='white'))+
  theme(legend.box.spacing=unit(0, "cm"))+
  theme(panel.background = element_rect(fill = 'white'))+
  theme(axis.line.x = element_line())+
  theme(axis.line.y = element_line())+
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))+ #sets the margin around the plot area; note: arugments correspond to (top, right, bottom, left)
  scale_color_manual("", 
                      values = c("ANPP"="dark green")) #defines a color scale for each data series and generates a legend

print(anpp_timeseries_plot)
```

```{r}
#respiration plot
respiration_timeseries_plot <- ggplot(data = app_timeseries, aes(x = date)) + #calls ggplot and stores the call in a graphics object called "app_timeseries_plot"
  geom_point(aes(y = respiration_mean, color = "Respiration"), size = 3)+ #plots our data as points, specify our data series via a color argument (to be defined later)
  geom_errorbar(mapping=aes(x=date, ymin=respiration_mean-respiration_std_err, ymax=respiration_mean+respiration_std_err), width=7, size=0.5, color="dark blue")+ #defines the size and values for standard error
  #formatting commands below
  scale_x_date(date_breaks="1 month", date_labels ="%b-%y", limit = c(as.Date("2017-05-01"), as.Date("2017-12-01")))+ #sets the scale for x axis
  ylim(c(-0.2,0.6))+ #defines upper and lower bound of y scale (otherwise R just guesses)
  labs(x = "Date", y = "Respiration (mg/hr)")+ #sets labels for each axes
  theme(legend.position=c(0.9,0.9))+ #positions read as (x,y), where x = 0 is left, y = 0 is bottom
  theme(legend.key=element_rect(fill='white'))+
  theme(legend.box.spacing=unit(0, "cm"))+
  theme(panel.background = element_rect(fill = 'white'))+
  theme(axis.line.x = element_line())+
  theme(axis.line.y = element_line())+
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))+ #sets the margin around the plot area; note: arugments correspond to (top, right, bottom, left)
  scale_color_manual("", 
                      values = c("Respiration"="dark blue")) #defines a color scale for each data series and generates a legend

print(respiration_timeseries_plot)
```

```{r}
#exporting graphics

ggsave("tr_anpp_timeseries.eps", anpp_timeseries_plot, width = 8, path = '~/Google Drive/WEEL/Tres Rios/datasets/tr-aquatic-primary-productivity/graphics/')
ggsave("tr_respiration_timeseries.eps", respiration_timeseries_plot, width = 8, path = '~/Google Drive/WEEL/Tres Rios/datasets/tr-aquatic-primary-productivity/graphics/')

```
